name = "Nyamcraft"
author = "Lnvll"
version = "0.6.7.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "36013216146a0d2158b334d5fcdf38333ba94dd265c3085fbd33c8bd9eeef8c5"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
