name = "Nyamcraft"
author = "Lnvll"
version = "0.6.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5f021ac60aa33970bcaa0695e4075df269b063a797da8384a2f35dbd640a3a71"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
